// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "AR Demo",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "AR Demo",
            targets: ["AppModule"],
            bundleIdentifier: "de.tobiaspott.playground.ardemo",
            teamIdentifier: "LR2W97LX43",
            displayVersion: "0.1",
            bundleVersion: "6",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "AR Features")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
